MAX_LABEL_LENGTH=20
DEBUG = False
DEBUG2 = False

STOP_USING_POS = True
ENABLE_LEMMATIZER = True
DO_RESUME_CHUNKING = False
PRUNE_RESUME = False
REMOVE_HEADERS = True
REMOVE_STOP_WORDS = True

PRINT_SOM_VECTORS = False
PRINT_ONE_GRAM = True
GRID_MULT = 5
GENERATE_IMAGE = True
TEXT_FILE_ENCODING = 'windows-1252'
MOVE_JD_PTR_INSIDE = True
ENABLE_FILE_LINE_CACHE = True

NUM_KEYWORDS_FOR_NAUKRI = 4
ENABLE_HDP=False

SEED = 0312

# production
#PRINT_SOM_VECTORS = False
#PRINT_ONE_GRAM = False
#GRID_MULT = 5
#DO_RESUME_CHUNKING = False
#PRUNE_RESUME = False
#GENERATE_IMAGE = True
